# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AudioLocator(object):
    def setupUi(self, AudioLocator):
        AudioLocator.setObjectName(_fromUtf8("AudioLocator"))
        AudioLocator.resize(899, 822)
        self.centralwidget = QtGui.QWidget(AudioLocator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_14 = QtGui.QSplitter(self.centralwidget)
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName(_fromUtf8("splitter_14"))
        self.screen = ScreenWidget(self.splitter_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.screen.sizePolicy().hasHeightForWidth())
        self.screen.setSizePolicy(sizePolicy)
        self.screen.setFrameShape(QtGui.QFrame.Box)
        self.screen.setFrameShadow(QtGui.QFrame.Raised)
        self.screen.setLineWidth(3)
        self.screen.setObjectName(_fromUtf8("screen"))
        self.splitter_13 = QtGui.QSplitter(self.splitter_14)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName(_fromUtf8("splitter_13"))
        self.splitter_11 = QtGui.QSplitter(self.splitter_13)
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName(_fromUtf8("splitter_11"))
        self.splitter_12 = QtGui.QSplitter(self.splitter_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_12.sizePolicy().hasHeightForWidth())
        self.splitter_12.setSizePolicy(sizePolicy)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName(_fromUtf8("splitter_12"))
        self.label_7 = QtGui.QLabel(self.splitter_12)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.x1Edit = QtGui.QLineEdit(self.splitter_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1Edit.sizePolicy().hasHeightForWidth())
        self.x1Edit.setSizePolicy(sizePolicy)
        self.x1Edit.setReadOnly(False)
        self.x1Edit.setObjectName(_fromUtf8("x1Edit"))
        self.y1Edit = QtGui.QLineEdit(self.splitter_12)
        self.y1Edit.setReadOnly(False)
        self.y1Edit.setObjectName(_fromUtf8("y1Edit"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_13)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter = QtGui.QSplitter(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_2 = QtGui.QLabel(self.splitter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.x2Edit = QtGui.QLineEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x2Edit.sizePolicy().hasHeightForWidth())
        self.x2Edit.setSizePolicy(sizePolicy)
        self.x2Edit.setReadOnly(False)
        self.x2Edit.setObjectName(_fromUtf8("x2Edit"))
        self.y2Edit = QtGui.QLineEdit(self.splitter)
        self.y2Edit.setReadOnly(False)
        self.y2Edit.setObjectName(_fromUtf8("y2Edit"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_13)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_5 = QtGui.QSplitter(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.label_5 = QtGui.QLabel(self.splitter_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.x3Edit = QtGui.QLineEdit(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x3Edit.sizePolicy().hasHeightForWidth())
        self.x3Edit.setSizePolicy(sizePolicy)
        self.x3Edit.setReadOnly(False)
        self.x3Edit.setObjectName(_fromUtf8("x3Edit"))
        self.y3Edit = QtGui.QLineEdit(self.splitter_5)
        self.y3Edit.setReadOnly(False)
        self.y3Edit.setObjectName(_fromUtf8("y3Edit"))
        self.splitter_9 = QtGui.QSplitter(self.splitter_13)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.splitter_10 = QtGui.QSplitter(self.splitter_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter_10.sizePolicy().hasHeightForWidth())
        self.splitter_10.setSizePolicy(sizePolicy)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.label_6 = QtGui.QLabel(self.splitter_10)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.x4Edit = QtGui.QLineEdit(self.splitter_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x4Edit.sizePolicy().hasHeightForWidth())
        self.x4Edit.setSizePolicy(sizePolicy)
        self.x4Edit.setReadOnly(False)
        self.x4Edit.setObjectName(_fromUtf8("x4Edit"))
        self.y4Edit = QtGui.QLineEdit(self.splitter_10)
        self.y4Edit.setReadOnly(False)
        self.y4Edit.setObjectName(_fromUtf8("y4Edit"))
        self.gridLayout.addWidget(self.splitter_14, 0, 0, 1, 1)
        AudioLocator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AudioLocator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 25))
        self.menubar.setDefaultUp(True)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        AudioLocator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AudioLocator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AudioLocator.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(AudioLocator)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        AudioLocator.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionHistory = QtGui.QAction(AudioLocator)
        self.actionHistory.setObjectName(_fromUtf8("actionHistory"))
        self.menuView.addAction(self.actionHistory)
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(AudioLocator)
        QtCore.QMetaObject.connectSlotsByName(AudioLocator)

    def retranslateUi(self, AudioLocator):
        AudioLocator.setWindowTitle(_translate("AudioLocator", "MainWindow", None))
        self.label_7.setText(_translate("AudioLocator", "Candidate 1:", None))
        self.x1Edit.setPlaceholderText(_translate("AudioLocator", "x", None))
        self.y1Edit.setPlaceholderText(_translate("AudioLocator", "y", None))
        self.label_2.setText(_translate("AudioLocator", "Candidate 2:", None))
        self.x2Edit.setPlaceholderText(_translate("AudioLocator", "x", None))
        self.y2Edit.setPlaceholderText(_translate("AudioLocator", "y", None))
        self.label_5.setText(_translate("AudioLocator", "Candidate 3:", None))
        self.x3Edit.setPlaceholderText(_translate("AudioLocator", "x", None))
        self.y3Edit.setPlaceholderText(_translate("AudioLocator", "y", None))
        self.label_6.setText(_translate("AudioLocator", "Candidate 4:", None))
        self.x4Edit.setPlaceholderText(_translate("AudioLocator", "x", None))
        self.y4Edit.setPlaceholderText(_translate("AudioLocator", "y", None))
        self.menuView.setTitle(_translate("AudioLocator", "View", None))
        self.toolBar.setWindowTitle(_translate("AudioLocator", "toolBar", None))
        self.actionHistory.setText(_translate("AudioLocator", "History", None))

from ScreenWidget import ScreenWidget
